DROP TABLE IF EXISTS public.customer;
CREATE TABLE public.customer (
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Идентификатор
	"name" varchar NOT NULL, -- Имя клиента
	lastname varchar NULL, -- Фамилия клиента
	tel varchar NULL, -- Телефон клиента
	email varchar NULL, -- Эл. почта клиента
	CONSTRAINT customer_pk PRIMARY KEY (id)
);
COMMENT ON COLUMN public.customer.id IS 'Идентификатор';
COMMENT ON COLUMN public.customer."name" IS 'Имя клиента';
COMMENT ON COLUMN public.customer.lastname IS 'Фамилия клиента';
COMMENT ON COLUMN public.customer.tel IS 'Телефон клиента';
COMMENT ON COLUMN public.customer.email IS 'Эл. почта клиента';


DROP TABLE IF EXISTS public.order_status;
CREATE TABLE public.order_status (
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar NOT NULL, -- Статус заказа
	CONSTRAINT order_status_pk PRIMARY KEY (id)
);
COMMENT ON COLUMN public.order_status."name" IS 'Статус заказа';


DROP TABLE IF EXISTS public.product;
CREATE TABLE public.product (
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar NOT NULL, -- Имя продукта
	descr varchar NULL, -- Описание
	"cost" float4 NOT NULL, -- Стоимость
	qty int2 DEFAULT 0 NOT NULL, -- Кол-во
	cat varchar NULL, -- Категория
	CONSTRAINT product_check1 CHECK ((cost >= (0)::double precision)),
	CONSTRAINT product_check2 CHECK ((qty >= 0)),
	CONSTRAINT product_pk PRIMARY KEY (id)
);
COMMENT ON COLUMN public.product."name" IS 'Имя продукта';
COMMENT ON COLUMN public.product.descr IS 'Описание';
COMMENT ON COLUMN public.product."cost" IS 'Стоимость';
COMMENT ON COLUMN public.product.qty IS 'Кол-во';
COMMENT ON COLUMN public.product.cat IS 'Категория';


DROP TABLE IF EXISTS public."order";
CREATE TABLE public."order" (
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	product_id int4 NOT NULL, -- ID Продукта
	customer_id int4 NOT NULL, -- ID Клиента
	ts timestamp DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL, -- Время заказа
	qty int4 DEFAULT 1 NOT NULL, -- Кол-во
	order_status_id int4 NOT NULL -- ID Статуса
);
CREATE INDEX order_id_idx ON public."order" USING btree (id, product_id, customer_id, ts);

-- Column comments

COMMENT ON COLUMN public."order".product_id IS 'ID Продукта';
COMMENT ON COLUMN public."order".customer_id IS 'ID Клиента';
COMMENT ON COLUMN public."order".ts IS 'Время заказа';
COMMENT ON COLUMN public."order".qty IS 'Кол-во';
COMMENT ON COLUMN public."order".order_status_id IS 'ID Статуса';

ALTER TABLE public."order" ADD CONSTRAINT order_customer_fk FOREIGN KEY (customer_id) REFERENCES public.customer(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public."order" ADD CONSTRAINT order_order_status_fk FOREIGN KEY (order_status_id) REFERENCES public.order_status(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public."order" ADD CONSTRAINT order_product_fk FOREIGN KEY (product_id) REFERENCES public.product(id) ON DELETE CASCADE ON UPDATE CASCADE;